### PR TITLE
Update external-content.html

### PR DESCRIPTION
**Pull request by jodekirk**
Changed ampersand to XML equivalent & amp; to make it valid utf-8 unicode/XML.

### CODE REVIEW

**Comment by jodekirk** [comment]
I signed it!

**Comment by blasten** [comment]
LGTM!

**Comment by blasten** [comment]
@jodekirk It doesn't seem like you signed the CLA. can you please verify that?

**Comment by jodekirk** [comment]
I signed it!

**Comment by blasten** [comment]
merged now. Thanks!

**Pull request merged**
