### PR TITLE
Adds defaultItem property

### PR DESCRIPTION
**Pull request by Westbrook**
Addresses #244

This property allows for the display of a fixes scrolling profile over the course of loading pages data responses to fill a fixed data set. Thereby you could:

```
<iron-list>
    <template>
        <div>
            <h1>[[item.title]]
        </div>
    <template>
</iron-list>
...
list.defaultItem = { title: 'Loading...' };
list.items = new Array(1000); //The list now displays 1000 placeholder items.
list.splice('items', 0, 1, {title: 'Actually Loaded'}); //Splices real content into the list
//repeat as needed with single items, arrays of items, etc.
```

Further information about this line of thinking can be found: https://medium.com/by-photoshelter/expanding-on-a-riff-photoshelter-in-the-polymer-js-community-d2af14253b2e#.c53z0kpg4

### CODE REVIEW

**Comment by blasten** [comment]
Thanks for the PR. I'm inclined to think that if someone wants a default item, they should set it via `list.items`.

**Comment by Westbrook** [comment]
At a handful of elements setting via `list.items` that way isn't an issue, but while being 96% slower than this PR the standard approach of actually building that array to publish into `this.items` starts to be costly if you're doing a lot of other processing on the page in question.

**Comment by blasten** [comment]
> starts to be costly if you're doing a lot of other processing on the page.

Sounds like a different issue to me. I think setting the placeholders via `list.items` should have almost the same perf because you are already creating an array of size `N`.

**Comment by Westbrook** [comment]
It's possible that you're right.... Maybe you're thinking of doing this is a smarter way than myself? https://jsperf.com/set-vs-default-4

**Comment by blasten** [comment]
Closing this PR in favor of adding a demo or reseting the item instance via `list.set('items.0', itemInstance);`

**Comment by Legioth** [comment]
@blasten You mentioned adding a demo in your last comment. Where can that demo be found?

**Pull request closed without merging**
