### PR TITLE
Make iron-list behave as a dumb list when parent's height is not spec…

### PR DESCRIPTION
**Pull request by freshp86**
…ified.

This allows the iron-list to behave as a dumb list where all elements are
always rendered, which is much more intuitive than previous behavior of
rendering only three elements, until the window is resized (or a resize event
was manually fired).

### CODE REVIEW

**Comment by freshp86** [comment]
@blasten Followed your instructions. Seems that tests need to be updated though. I have no idea how to run them.

**Comment by blasten** [comment]
I think it's travis: https://www.traviscistatus.com/incidents/lp492hx0z1my

**Comment by blasten** [comment]
@freshp86 one test needs to be updated https://github.com/PolymerElements/iron-list/blob/4f893a5193e0540c07177f4dbf3e7ee298ac8543/test/physical-count.html#L95.  That could just become  `assert.equal(list._physicalCount, 0);`

**Comment by blasten** [comment]
LGTM

**Pull request merged**
