### PR TITLE
Allow extra pages to be configurable

### PR DESCRIPTION
**Pull request by danbeam**

### CODE REVIEW

**Comment by danbeam** [comment]
BTW: should the tests be calling `fire('iron-resize')` or `fire('resize')`?

**Comment by blasten** [comment]
yeah, it should be `iron-resize`.  Let me review this PR with @kevinpschaaf. I'm little bit hesitant about exposing these properties instead of determining it for the user and decreasing the first paint time if that is the issue.

**Comment by blasten** [comment]
@danbeam @kevinpschaaf and I think that the list can just expose `extraPages` and we should fix `DEFAULT_PHYSICAL_COUNT `.

**Comment by danbeam** [comment]
@blasten @kevinpschaaf reverted `minimumItems`, only `extraPages` is left now.  Let me know if you want me to write a test.

**Comment by blasten** [comment]
@danbeam https://github.com/PolymerElements/iron-list/pull/136 was merged and it should help to reduce first paint time. I will close this PR for now since we may not need to configure this value.

**Pull request closed without merging**
