### PR TITLE
Undo some modulizer funkyness

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Comment by e111077** [comment]
Things are failing

**Comment by rictic** [comment]
Huh, were they passing at master?

**Comment by keanulee** [comment]
Maybe `Polymer` identifier is clashing with `Polymer.Collection` type? https://github.com/PolymerElements/iron-list/blob/master/iron-list.js#L493

**Comment by keanulee** [comment]
`Polymer.Collection` is no longer a thing as of Polymer 2, so `this._collection` and related code paths could be removed.

**Comment by keanulee** [comment]
Nope, removing references to `Polymer.Collection` didn't work for me locally. Something with not importing `Polymer` as some other identifier (e.g. `Polymer$0`).

**Comment by e111077** [comment]
I think that the Polymer namespace may be conflicting with the Typescriptified Polymer namespace. I believe that typescript may be looking into polymer-fn for these types instead of the externs

**Pull request merged**
